url: http://cnhalo.com
title: CNHALO
subtitle: HENRY_HUANGS 要写点什么.
author: HENRY_HUANGS
simple_search: http://google.com/search
description: 要写点什么.

# Owner/author information
owner:
  name:           HENRY_HUANGS
  avatar:         avatar.jpg
  bio:            "争四狂魔的追随者 / <br/>程序猿 / <br/>一点寒芒先到，随后枪出如龙"
  email:
  # Social networking links used in footer. Update and remove as you like.
  twitter:        
  facebook:       
  github:         
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:   
  weibo: 626242034  

# Background image to be tiled on all pages
background: 

# Links to include in top navigation
# For external links add external: true
links:
  - title: 轻博客
    url: http://onecircle.lofter.com/
    external: true
  - title: Gallery
    url: http://gallery.cnhalo.com
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
highlighter: pygments
markdown:    kramdown
excerpt_separator: ""
plugins: _plugins

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# Duoshuo Comments
duoshuo_comments: true
duoshuo_short_name: henryhuang
duoshuo_asides_num: 10      # 侧边栏评论显示条目数
duoshuo_asides_avatars: 0   # 侧边栏评论是否显示头像
duoshuo_asides_time: 0      # 侧边栏评论是否显示时间
duoshuo_asides_title: 0     # 侧边栏评论是否显示标题
duoshuo_asides_admin: 0     # 侧边栏评论是否显示作者评论
duoshuo_asides_length: 18   # 侧边栏评论截取的长度


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

icp: 沪ICP备12046790号-1
